#ifndef _NT_DEF_H
#define _NT_DEF_H
#include <windows.h>

typedef	HMODULE ( WINAPI*PFN_LOADLIBRARYA ) ( LPCSTR lpLibFileName );
typedef	HMODULE ( WINAPI*PFN_LOADLIBRARYW ) ( LPCWSTR lpLibFileName );
typedef	HANDLE ( WINAPI * PFN_CREATEFILEA )(		LPCTSTR lpFileName,		DWORD dwDesiredAccess,		DWORD dwShareMode,		LPSECURITY_ATTRIBUTES lpSecurityAttributes,		DWORD dwCreationDisposition,		DWORD dwFlagsAndAttributes, 		HANDLE hTemplateFile	);
typedef	BOOL (WINAPI * PFN_CREATEPROCESSINTERNALA)(HANDLE, LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID, LPCSTR,LPSTARTUPINFOA,LPPROCESS_INFORMATION, PHANDLE);

#endif